version: '3'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"  # Add space after the dash and use quotes around the mapping
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs